language: php
php:
  - 5.5
  - 5.6
  - hhvm

before_install:
  - sudo apt-get update -qq -y;
  - sudo apt-get install -qq -y git;
  - cd /tmp && git clone git@github.com:allegro/php-protobuf.git && cd php-protobuf
  - phpize && ./configure && make install
  - echo 'extension = "/usr/lib/php5/20121212/protobuf.so"' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini

before_script:
  - composer self-update
  - composer install

script:
  - bin/phpunit